use_frameworks!

target 'SwiftyForms_Example' do
	pod 'SwiftyForms', :path => '../'
	
	target 'SwiftyForms_Tests' do
		inherit! :search_paths
		pod 'Quick', :git => 'https://github.com/Quick/Quick', :branch => 'swift-3.0'
		pod 'Nimble', :git => 'https://github.com/Quick/Nimble'
	end
end
